# Site settings
name: Ballet
title: Ballet
email: ballet@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Ballet
# baseurl:  # the subpath of your site, e.g. /blog/
# url: "https://ballet.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty

# Build settings
markdown: kramdown

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - README.md
  - .jekyll-cache
  - bootstrap-vars.scss
  - vendor

keep_files:
  - _site/css
  - _site/js

include: ['_pages']
